//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadersCompanion.App_Code.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int bookID { get; set; }
        public Nullable<int> bookNumber { get; set; }
        public string bookTitle { get; set; }
    }
}
