//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadersCompanion.App_Code.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemDescriptions = new HashSet<ItemDescription>();
        }
    
        public int itemID { get; set; }
        public string itemName { get; set; }
        public string itemType { get; set; }
        public Nullable<int> firstMentionBook { get; set; }
        public Nullable<int> firstMentionChapter { get; set; }
        public Nullable<int> eventDate { get; set; }
    
        public virtual ICollection<ItemDescription> ItemDescriptions { get; set; }
    }
}
